version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16.1
      - image: ethereum/client-go:v1.9.14
        entrypoint: /bin/sh
        command: -c "yes '' | geth --dev --dev.period 15 --http --http.addr '0.0.0.0' --http.port 8545 --http.api 'eth,net,web3,account,admin,personal' --unlock '0' --allow-insecure-unlock"
    steps:
      - checkout
      - run: |
          yarn install
          yarn test

workflows:
  version: 2
  test-publish:
    jobs:
      - test
